const data = [
    { id: 1, name: "RJ Barrett", img: './mainImgs/RJ.png', postImg: './postImgs/RJ2.jpeg', position: 'Shooting Guard', age: '21', number: '9', height: '6-6', weight: '214lbs', content: "Rowan Alexander 'RJ' Barrett Jr. (born June 14, 2000) is a Canadian professional basketball player for the New York Knicks of the National Basketball Association (NBA). A shooting guard and small forward, he was selected third overall in the 2019 NBA Draft by the New York Knicks after one year with the Duke Blue Devils program under coach Mike Krzyzewski."},
    { id: 2, name: "Alec Burks", img: './mainImgs/alec.png', postImg: './postImgs/alec2.jpeg', position: 'Shooting Guard', age: '30', number: '18', height: '6-6', weight: '214lbs', content: "Alec Burks (born July 20, 1991) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). He was selected by the Utah Jazz as the 12th overall pick in the 2011 NBA draft. Burks primarily plays the shooting guard position."},
    { id: 3, name: "Evan Fournier", img: './mainImgs/evan.png', postImg: './postImgs/evan2.jpeg', position: 'Shooting Guard', age: '29', number: '13', height: '6-6', weight: '205lbs', content: "Evan Mehdi Fournier (born 29 October 1992) is a French professional basketball player for the New York Knicks of the National Basketball Association (NBA). He played junior basketball at the French INSEP academy from 2007 to 2009."},
    { id: 4, name: "Taj Gibson", img: './mainImgs/taj.png', postImg: './postImgs/taj2.jpg', position: 'Center', age: '36', number: '67', height: '6-9', weight: '232lbs', content: "Taj Jami Gibson (born June 24, 1985) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). Gibson played college basketball for the USC Trojans and was selected 26th overall by the Chicago Bulls in the 2009 NBA draft."},
    { id: 5, name: "Quentin Grimes", img: './mainImgs/grimes.png', postImg: './postImgs/grimes2.jpeg', position: 'Shooting Guard', age: '21', number: '6', height: '6-4', weight: '210lbs', content: "Quentin Marshall Grimes (born May 8, 2000) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). He played college basketball for the Kansas Jayhawks and the Houston Cougars."},
    { id: 6, name: "Kevin Knox", img: './mainImgs/knox.png', postImg: './postImgs/knox2.jpeg', position: 'Small Forward', age: '22', number: '20', height: '6-7', weight: '215lbs', content: "Kevin Devon Knox II (born August 11, 1999) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). He played college basketball for the Kentucky Wildcats and attended high school at Tampa Catholic High School."},
    { id: 7, name: "Miles McBride", img: './mainImgs/miles.png', postImg: './postImgs/mcbride2.jpeg', position: 'Point Guard', age: '21', number: '2', height: '6-1', weight: '195lbs', content: "Miles James 'Deuce' McBride (born September 8, 2000) is an American basketball player for the New York Knicks of the National Basketball Association (NBA). He played college basketball for the West Virginia Mountaineers."},
    { id: 8, name: "Nerlens Noel", img: './mainImgs/noel.png', postImg: './postImgs/noel2.jpeg', position: 'Center', age: '27', number: '3', height: '6-11', weight: '220lbs', content: "Nerlens Noel (born April 10, 1994) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). His collegiate basketball career ended in his first season with a tear of his anterior cruciate ligament (ACL) at the University of Kentucky. Noel was drafted with the sixth overall pick in the 2013 NBA draft by the New Orleans Pelicans. His rights were later traded to the Philadelphia 76ers."},
    { id: 9, name: "Immanuel Quickley", img: './mainImgs/quick.png', postImg: './postImgs/quickley2.jpeg', position: 'Shooting Guard', age: '22', number: '5', height: '6-3', weight: '190lbs', content: "Immanuel Jaylen Quickley (born June 17, 1999) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). He played college basketball for the Kentucky Wildcats."},
    { id: 10, name: "Julius Randle", img: './mainImgs/julius.png', postImg: './postImgs/julius2.jpeg', position: 'Power Forward', age: '26', number: '30', height: '6-8', weight: '250lbs', content: "Julius Deion Randle (born November 29, 1994) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). In his second season with the Knicks in 2020–21, he was a first-time NBA All-Star and was awarded the NBA Most Improved Player Award."},
    { id: 11, name: "Mitchell Robinson", img: './mainImgs/mitchell.png', postImg: './postImgs/mitchell2.jpeg', position: 'Center', age: '23', number: '23', height: '6-6', weight: '214lbs', content: "Mitchell Robinson III (born April 1, 1998) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). He was selected with the 36th overall pick in the 2018 NBA draft. Before beginning his professional career, he gained national coverage for withdrawing from his commitment to attend Western Kentucky University to instead dedicate the entire 2017–18 season for training on his own, being the first player to make such a decision."},
    { id: 12, name: "Derrick Rose", img: './mainImgs/derrick.png', postImg: './postImgs/rose2.jpeg', position: 'Point Guard', age: '33', number: '4', height: '6-2', weight: '200lbs', content: "Derrick Martell Rose (born October 4, 1988) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). He played one year of college basketball for the Memphis Tigers before being drafted first overall by his hometown Chicago Bulls in the 2008 NBA draft. He was named the NBA Rookie of the Year and also became the youngest player to win the NBA Most Valuable Player Award in 2011 at age 22."},
    { id: 13, name: "Luka Samanic", img: './mainImgs/luka.png', postImg: './postImgs/luka2.jpeg', position: 'Power Forward', age: '21', number: '9', height: '6-10', weight: '227lbs', content: "Luka Šamanić (born 9 January 2000) is a Croatian professional basketball player for the New York Knicks of the National Basketball Association (NBA), on a two-way contract with the Westchester Knicks of the NBA G League. A power forward, he was drafted 19th overall by the San Antonio Spurs in the 2019 NBA draft."},
    { id: 14, name: "Wayne Selden", img: './mainImgs/selden.png', postImg: './postImgs/selden2.jpeg', position: 'Forward', age: '27', number: '11', height: '6-4', weight: '232lbs', content: "Wayne Anthony Selden Jr. (born September 30, 1994) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). He played college basketball for the Kansas Jayhawks."},
    { id: 15, name: "Jericho Sims", img: './mainImgs/sims.png', postImg: './postImgs/sims2.jpeg', position: 'Center', age: '23', number: '45', height: '6-9', weight: '250lbs', content: "Jericho Eduard Sims (born October 20, 1998) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA), on a two-way contract with the Westchester Knicks of the NBA G League. He played college basketball for the Texas Longhorns."},
    { id: 16, name: "Obi Toppin", img: './mainImgs/obi.png', postImg: './postImgs/obi2.jpeg', position: 'Power Forward', age: '23', number: '1', height: '6-9', weight: '220lbs', content: "Obadiah Richard 'Obi' Toppin Jr. (born March 4, 1998) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). A power forward, he played college basketball for the Dayton Flyers."},
    { id: 17, name: "Kemba Walker", img: './mainImgs/kemba.png', postImg: './postImgs/kemba2.jpeg', position: 'Point Guard', age: '31', number: '8', height: '6-0', weight: '184lbs', content: "Kemba Hudley Walker (born May 8, 1990) is an American professional basketball player for the New York Knicks of the National Basketball Association (NBA). Walker was picked ninth overall by the Charlotte Bobcats in the 2011 NBA draft. He grew up in The Bronx, New York City. After graduating from Rice High School in 2008, he played college basketball for the Connecticut Huskies. In their 2010–11 season, Walker was the nation's second-leading scorer and was named consensus first-team All-American; he also led the Huskies to the 2011 NCAA championship and claimed the tournament's Most Outstanding Player award. Walker is a four-time NBA All-Star."}
  ];
  
  const list = () => {
    return [...data] 
  }; 
  
  const find = (id) => {
    const post = data.find(post => post.id === Number(id));
    return {...post}; 
  }
  
  module.exports = { list: list, find: find };